### ISSUE TITLE
How

### ISSUE THREAD

**Issue by CEGLincoln** [yxliang01/cs1010-fun-stuff#3]
How do you create a directory in Github?

**Comment by yxliang01** [comment]
As far as I know, you need to clone the repo to local. Then you create locally. At the end, you push back to github... Not like file, I don't see any way to create using this web interface.

**Comment by yxliang01** [comment]
By the way, @CEGLincoln Please change your issue title to be something making sense :joy: And, if this question is resolved, please close this issue.
