### ISSUE TITLE
15-oct-2018 tutorial: assignment 4 or general Q&A

### ISSUE THREAD

**Issue by yxliang01** [yxliang01/cs1010-fun-stuff#4]
Hello,

For tutorial on 15-oct-2018, which option you would like to pick? Please comment below by **1am, 15-oct-2018**.

**Comment by hanskw4267** [comment]
Assignment 5 pls

**Comment by x3chillax** [comment]
As05 plox

**Comment by yxliang01** [comment]
Times up but not enough participants...
